---
- name: Configure paths
  lineinfile:
    dest:   ~/.profile
    line:   "{{ line_item.content }}"
    state:  present
    regexp: "{{ line_item.regexp }}"
  loop_control:
    loop_var: line_item
  with_items:
    - content:  "export RUBYMOTION_ANDROID_NDK={{ ansible_env['HOME'] }}/.rubymotion-android/ndk"
      regexp:   ^export RUBYMOTION_ANDROID_NDK=
    - content:  "export RUBYMOTION_ANDROID_SDK={{ ansible_env['HOME'] }}/.rubymotion-android/sdk"
      regexp:   ^export RUBYMOTION_ANDROID_SDK=

- name:   Run RubyMotion's Android Setup
  shell:  motion android-setup
  args:
    creates:  ~/.rubymotion-android/

- name: Install emulation hardware acceleration
  homebrew_cask:
    name:   intel-haxm
    state:  present

- name: Create Android Virtual Device
  shell:  echo no | ~/.rubymotion-android/sdk/tools/android create avd --target android-23 --name Devdroid --tag android-tv
  args:
    creates:  ~/.android/avd/Devdroid.ini
